# Generated by Django 3.1.1 on 2021-03-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
